platform :ios, '10.0'

target 'PaymentDemo' do
  use_frameworks!

    pod 'Alamofire', '~> 4.0.0'
    pod 'ObjectMapper', '~> 2.0.0'
    pod 'PKHUD', :git => 'https://github.com/toyship/PKHUD.git'
  
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |configuration|
			configuration.build_settings['SWIFT_VERSION'] = '3.0'
		end
	end
end
